name: Deploy Food Ordering System API Server to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute remote deployment script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ENV_CONTENT=$(cat <<'EOF'
            PORT=${{ secrets.PORT }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRE_IN=${{ secrets.JWT_EXPIRE_IN }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
            EOF
            )

            /home/njerka/apps/deploy.sh \
              --port 5006 \
              --subdomain food \
              --domain njerka.xyz \
              --git https://github.com/ahmedG3far44/ordering-food-system.git \
              --dir "./server" \
              --env "$ENV_CONTENT"
